apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: default
type: Opaque
stringData:
  token: "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"
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gpt-oss-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-gpt-oss-1
  template:
    metadata:
      labels:
        app: vllm-gpt-oss-1
    spec:
      restartPolicy: Always
      runtimeClassName: nvidia
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.10.2
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |              
              vllm serve openai/gpt-oss-20b \
                --host 0.0.0.0 \
                --port 8000 \
                --trust-remote-code \
                --async-scheduling \
                --gpu-memory-utilization 0.90 \
                --enable-auto-tool-choice \
                --tool-call-parser openai
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "4"
              memory: 12Gi
            limits:
              cpu: "12"
              memory: 32Gi
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: hf-cache
          persistentVolumeClaim:
            claimName: vllm-model-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-gpt-oss-1
  namespace: default
  labels:
    type: external
spec:
  selector:
    app: vllm-gpt-oss-1
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
