apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-dockerhub-secret
spec:
  rules:
  - name: add-imagepullsecret
    match:
      resources:
        kinds:
        - Pod
          # namespaces:
          # - monitoring
    mutate:
      patchStrategicMerge:
        spec:
          imagePullSecrets:
          - name: docker-hub-registry-secret

