apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: admin
spec:
  limits:
  - default:
      cpu: 8
      memory: 25Gi
    defaultRequest:
      cpu: 0.5
      memory: 512Mi
    type: Container
