apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kserve-deployer
  namespace: kserve-test
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kserve-deployer-binding
  namespace: kserve-test
subjects:
  - kind: ServiceAccount
    name: default-editor
    namespace: admin
roleRef:
  kind: Role
  name: kserve-deployer
  apiGroup: rbac.authorization.k8s.io

